INSERT INTO app_country (ID, NAME, NAME_FR, ISO, ISO3, FIPS, CONTINENT, PHONE_PREFIX, POSTAL_CODE, LANGUAGES, CURRENCY_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(1, 'Afghanistan', 'Afghanistan', 'AF', 'AFG', 'AF', 'AS', '93', '', 'fa-AF,ps,uz-AF,tk', 3, '2017-07-18 23:00:00', NULL, NULL);
INSERT INTO app_country (ID, NAME, NAME_FR, ISO, ISO3, FIPS, CONTINENT, PHONE_PREFIX, POSTAL_CODE, LANGUAGES, CURRENCY_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(2, 'Albania', 'Albanie', 'AL', 'ALB', 'AL', 'EU', '355', '', 'sq,el', 1, '2017-07-18 23:00:00', NULL, NULL);

INSERT INTO app_user (USER_ID, USER_EMAIL, USER_PASSWORD, CREATION_DATE, UPDATING_DATE, DELETING_DATE, USER_NAME, FIRST_NAME, LAST_NAME, ADRESS,  PHONE, STATUS, COUNTRY_ID_FK,BIRTHDAY,facebook_id,google_id) 
VALUES (1, 'issam.benbelgacem@esprit.tn', 'azerty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'issam', 'issam', 'benbelgacem', 'rades','23881505', 'VALIDATE',2,'1990-07-18',1,1);
INSERT INTO app_role (ROLE_ID, USER_ID, ROLE, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES (NULL, '1', 'ADMIN', NOW(), NOW(), NULL);


INSERT INTO app_user (USER_ID, USER_EMAIL, USER_PASSWORD, CREATION_DATE, UPDATING_DATE, DELETING_DATE, USER_NAME, FIRST_NAME, LAST_NAME, ADRESS,  PHONE, STATUS, COUNTRY_ID_FK,BIRTHDAY) 
VALUES (2, '3issam901@gmail.com', 'azerty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'issam', 'issam', 'benbelgacem', 'rades','23881505', 'VALIDATE',2,'1990-07-18');
INSERT INTO app_role (ROLE_ID, USER_ID, ROLE, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES (NULL, '2', 'USER', NOW(), NOW(), NULL);

INSERT INTO app_user (USER_ID, USER_EMAIL, USER_PASSWORD, CREATION_DATE, UPDATING_DATE, DELETING_DATE, USER_NAME, FIRST_NAME, LAST_NAME, ADRESS,  PHONE, STATUS, COUNTRY_ID_FK,BIRTHDAY) 
VALUES (3, 'khayri.ksiksi@esprit.tn', 'azerty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'khayri', 'khayri', 'ksiksi', 'medenien','23881505', 'VALIDATE',2,'1990-07-18');
INSERT INTO app_role (ROLE_ID, USER_ID, ROLE, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES (NULL, '2', 'USER', NOW(), NOW(), NULL);

INSERT INTO app_user (USER_ID, USER_EMAIL, USER_PASSWORD, CREATION_DATE, UPDATING_DATE, DELETING_DATE, USER_NAME, FIRST_NAME, LAST_NAME, ADRESS,  PHONE, STATUS, COUNTRY_ID_FK,BIRTHDAY) 
VALUES (4, 'khayri.ksiksi@allence.tn', 'azerty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'khayri', 'khayri', 'ksiksi', 'medenien','23881505', 'VALIDATE',2,'1990-07-18');
INSERT INTO app_role (ROLE_ID, USER_ID, ROLE, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES (NULL, '2', 'USER', NOW(), NOW(), NULL);

INSERT INTO app_user (USER_ID, USER_EMAIL, USER_PASSWORD, CREATION_DATE, UPDATING_DATE, DELETING_DATE, USER_NAME, FIRST_NAME, LAST_NAME, ADRESS,  PHONE, STATUS, COUNTRY_ID_FK,BIRTHDAY) 
VALUES (5, 'ahmed.ksiksi@allence.tn', 'azerty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'khayri', 'khayri', 'ksiksi', 'medenien','23881505', 'VALIDATE',2,'1990-07-18');
INSERT INTO app_role (ROLE_ID, USER_ID, ROLE, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES (NULL, '2', 'USER', NOW(), NOW(), NULL);

INSERT INTO app_template_mail (ID, OBJECT, BODY, EMAIL_KEY, CREATION_DATE, UPDATING_DATE, DELETING_DATE) 
VALUES (NULL, '[CHOSA] confirmation inscription', 'test from chosa.com', 'CompteConfirmation', '2017-07-20 12:44:49', '2017-08-15 16:06:02', NULL);
INSERT INTO app_template_mail (ID, OBJECT, BODY, EMAIL_KEY, CREATION_DATE, UPDATING_DATE, DELETING_DATE) 
VALUES(NULL, '[CHOSA] Request to confirm your email address', 'test from chosa.com', 'EmailConfirmation', '2017-11-06 19:04:46', '2017-11-14 10:24:45', NULL); 
INSERT INTO app_template_mail (ID, OBJECT, BODY, EMAIL_KEY, CREATION_DATE, UPDATING_DATE, DELETING_DATE)
VALUES(NULL, '[CHOSA] Your password request', 'test from chosa.com','MotPassPerdu', '2017-11-06 19:04:46', '2017-11-14 10:24:19', NULL);

INSERT INTO app_training_center (CENTER_ID, NAME, LOGO_FILE_ID_FK, MANAGER_USER_ID_FK, ADRESS, PHONE, STATUS, CREATION_DATE, UPDATING_DATE, DELETING_DATE, TRAINING_CENTER_COUNTRY_ID_FK)
VALUES (1, 'B2B', NULL, '1', 'montplaisir', '23881505', 'REQUEST', '2017-11-15 17:20:08', '2017-11-15 17:20:08', NULL, '1');
INSERT INTO app_training_center (CENTER_ID, NAME, LOGO_FILE_ID_FK, MANAGER_USER_ID_FK, ADRESS, PHONE, STATUS, CREATION_DATE, UPDATING_DATE, DELETING_DATE, TRAINING_CENTER_COUNTRY_ID_FK)
VALUES
(2, 'B2B', NULL, '1', 'montplaisir', '23881505', 'REQUEST', '2017-11-15 17:20:08', '2017-11-15 17:20:08', NULL, '1');
INSERT INTO app_training_center (CENTER_ID, NAME, LOGO_FILE_ID_FK, MANAGER_USER_ID_FK, ADRESS, PHONE, STATUS, CREATION_DATE, UPDATING_DATE, DELETING_DATE, TRAINING_CENTER_COUNTRY_ID_FK)
VALUES
(3, 'dentaire', NULL, '1', 'montplaisir', '23881505', 'REQUEST', '2017-11-16 14:55:03', '2017-11-16 14:55:03', NULL, '1');
INSERT INTO app_training_center (CENTER_ID, NAME, LOGO_FILE_ID_FK, MANAGER_USER_ID_FK, ADRESS, PHONE, STATUS, CREATION_DATE, UPDATING_DATE, DELETING_DATE, TRAINING_CENTER_COUNTRY_ID_FK)
VALUES
(4, 'dentaire', NULL, '1', 'montplaisir', '23881505', 'REQUEST', '2017-11-16 14:55:03', '2017-11-16 14:55:03', NULL, '1');
/* training centre program */
INSERT INTO app_training_center_program
(TRAINING_CENTER_PROGRAM_ID, PROGRAM_DURATION, PROGRAM_NAME, TRAINING_CENTER_PROGRAM_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES 
(1, '6', 'Programme 4 eme', '1', '2017-11-15 17:31:32', '2017-11-15 17:31:32', NULL);
INSERT INTO app_training_center_program(TRAINING_CENTER_PROGRAM_ID, PROGRAM_DURATION, PROGRAM_NAME, TRAINING_CENTER_PROGRAM_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES 
(2, '6', '3 eme', '2', '2017-11-16 14:55:26', '2017-11-16 14:55:26', NULL);
/* training centre class */
INSERT INTO app_training_center_class (TRAINING_CENTER_CLASS_ID, CLASS_NAME, TEACHER_USER_ID_FK, TRAINING_CENTER_ID_FK, PROGRAM_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(15, 'class', 2, 3, 1, '2017-11-17 13:04:37', '2017-11-20 10:13:49', NULL);

INSERT INTO app_training_center_theme (TRAINING_CENTER_THEME_ID, THEME_NAME, THEME_DESCRIPTION, THEME_ORDRE, PROGRAM_THEME_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(6, 'Summer', 'theme for summer', 1, 1, '2017-11-20 14:21:33', '2017-11-20 14:21:33', NULL);
INSERT INTO app_training_center_theme (TRAINING_CENTER_THEME_ID, THEME_NAME, THEME_DESCRIPTION, THEME_ORDRE, PROGRAM_THEME_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(7, 'Spring', 'theme for Spring', 2, 1, '2017-11-17 10:30:26', '2017-11-17 10:30:26', NULL);
INSERT INTO app_training_center_theme (TRAINING_CENTER_THEME_ID, THEME_NAME, THEME_DESCRIPTION, THEME_ORDRE, PROGRAM_THEME_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(8, 'Winter', 'theme for Winter', 3, 1, '2017-11-17 10:29:35', '2017-11-17 10:29:35', NULL);
INSERT INTO app_training_center_theme (TRAINING_CENTER_THEME_ID, THEME_NAME, THEME_DESCRIPTION, THEME_ORDRE, PROGRAM_THEME_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(9, 'Autumn', 'theme for autumn', 4, 1, '2017-11-17 10:28:48', '2017-11-17 10:28:48', NULL);
INSERT INTO app_training_center_theme (TRAINING_CENTER_THEME_ID, THEME_NAME, THEME_DESCRIPTION, THEME_ORDRE, PROGRAM_THEME_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(10, 'theme espagnol', 'exercice pour la langue espagnol', 1, 1, '2017-11-17 13:21:24', '2017-11-17 13:21:24', NULL);
INSERT INTO app_training_center_theme (TRAINING_CENTER_THEME_ID, THEME_NAME, THEME_DESCRIPTION, THEME_ORDRE, PROGRAM_THEME_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(11, 'theme anglais ', 'exercice pour la langue anlgais ', 2, 1, '2017-11-17 13:23:43', '2017-11-17 13:23:43', NULL);

/*family */
INSERT INTO app_family (FAMILY_ID, FAMILY_NAME, ADRESS, COUNTRY_ID_FK, PHONE, MANAGER_USER_ID_FK, LOGO_FILE_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(1, 'ksiksi', 'rue nil', 1, '24403181', 1, NULL, '2017-11-17 10:14:01', '2017-11-17 10:14:01', NULL);
INSERT INTO app_family (FAMILY_ID, FAMILY_NAME, ADRESS, COUNTRY_ID_FK, PHONE, MANAGER_USER_ID_FK, LOGO_FILE_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(2, 'ben belgacem', 'rades', 2, '64876949',2, NULL, '2017-11-17 11:01:49', '2017-11-17 11:01:49', NULL);
/*family member */
INSERT INTO app_family_member (FAMILY_MEMBER_ID, ROLE, USER_ID_FK, FAMILY_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(1, 'CHILD', 2, 1, '2017-11-17 11:03:29', '2017-11-28 13:34:58', NULL);
INSERT INTO app_family_member (FAMILY_MEMBER_ID, ROLE, USER_ID_FK, FAMILY_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(2, 'CHILD', 2, 2, '2017-11-17 11:04:16', '2017-11-17 11:04:16', NULL);
INSERT INTO app_family_member (FAMILY_MEMBER_ID, ROLE, USER_ID_FK, FAMILY_ID_FK, CREATION_DATE, UPDATING_DATE, DELETING_DATE) VALUES
(3, 'CHILD', 2, 1, '2017-11-17 11:04:56', '2017-11-17 11:04:56', NULL);
