-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Client :  127.0.0.1
-- Généré le :  Lun 30 Octobre 2017 à 16:18
-- Version du serveur :  5.6.17
-- Version de PHP :  5.5.12

/*SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
*/

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données :  chosa
--

-- --------------------------------------------------------

--
-- Structure de la table app_category
--

CREATE TABLE app_category(
  CATEGORY_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  CATEGORY_NAME varchar(255) NOT NULL,
  CATEGORY_PARENT_ID_FK bigint NOT NULL,
  USER_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp  NOT NULL ,
  UPDATING_DATE timestamp  NOT NULL ,
  DELETING_DATE timestamp DEFAULT  NULL ,
  PRIMARY KEY(CATEGORY_ID));

-- --------------------------------------------------------

--
-- Structure de la table app_country
--

CREATE TABLE  app_country (
  ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  NAME varchar(50) NULL,
  NAME_FR varchar(50) NULL,
  ISO varchar(3) NULL,
  ISO3 varchar(5) NULL,
  FIPS varchar(3) NULL,
  CONTINENT varchar(3) NULL,
  PHONE_PREFIX varchar(45) NULL,
  POSTAL_CODE varchar(45) NULL,
  LANGUAGES varchar(45) NULL,
  CURRENCY_ID_FK bigint NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NULL ,
  DELETING_DATE timestamp NULL ,
  PRIMARY KEY (ID),
  
) 


--
-- Structure de la table app_exercice
--

CREATE TABLE  app_exercice (
  EXERCICE_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  NAME varchar(255) NOT NULL,
  LEVEL varchar(255) NOT NULL,
  URL varchar(255) NOT NULL,
  URL_CALLBACK varchar(255) NOT NULL,
  Status varchar(255) NOT NULL,
  USER_EXECICE_ID_FK bigint NOT NULL,
  PICTURE_ID_FK bigint NOT NULL,
  EXERCICE_FILE_ID_FK bigint NOT NULL,
  CATEGORY_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL ,
  PRIMARY KEY (EXERCICE_ID)
  ) ;

-- --------------------------------------------------------

--
-- Structure de la table app_family
--

CREATE TABLE  app_family (
  FAMILY_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  FAMILY_NAME varchar(255) NOT NULL,
  ADRESS varchar(100) NOT NULL,
  COUNTRY_ID_FK bigint NOT NULL,
  PHONE varchar(50) NOT NULL,
  MANAGER_USER_ID_FK bigint NOT NULL,
  LOGO_FILE_ID_FK bigint NULL,
  CREATION_DATE timestamp NOT NULL,
  UPDATING_DATE timestamp NOT NULL,
  DELETING_DATE timestamp NULL ,
  PRIMARY KEY (FAMILY_ID)
);
-- --------------------------------------------------------

--
-- Structure de la table app_family_member
--

CREATE TABLE  app_family_member (
  FAMILY_MEMBER_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  ROLE varchar(255) NOT NULL,
  USER_ID_FK bigint NOT NULL,
  FAMILY_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL,
  UPDATING_DATE timestamp NOT NULL,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (FAMILY_MEMBER_ID)
) ;

-- --------------------------------------------------------

--
-- Structure de la table app_file
--

CREATE TABLE  app_file (
  FILE_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  FILE_NAME varchar(255) NOT NULL,
  PATH varchar(255) NOT NULL,
  USER_FILE_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (FILE_ID)
) ;

-- --------------------------------------------------------

--
-- Structure de la table app_history
--

CREATE TABLE  app_history (
  HISTORY_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  SCORE bigint NOT NULL,
  USER_ID_FK bigint NOT NULL,
  EXERCICE_ID_FK bigint NOT NULL,
  Status varchar(255) NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (HISTORY_ID));

-- --------------------------------------------------------

--
-- Structure de la table app_reviews
--

CREATE TABLE  app_reviews (
  REVIEWS_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  SCORE int NOT NULL,
  USER_ID_FK bigint NOT NULL,
  EXERCICE_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (REVIEWS_ID)
) ;

-- --------------------------------------------------------

--
-- Structure de la table app_role
--

CREATE TABLE  app_role (
  ROLE_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  USER_ID bigint NOT NULL,
  ROLE varchar(255) NOT NULL,
  CREATION_DATE timestamp NOT NULL,
  UPDATING_DATE timestamp NOT NULL,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (ROLE_ID)
  
);



--
-- Structure de la table app_training_center
--

CREATE TABLE  app_training_center (
  CENTER_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  NAME varchar(255) NOT NULL,
  LOGO_FILE_ID_FK bigint NULL,
  MANAGER_USER_ID_FK bigint NOT NULL,
  ADRESS varchar(255) NOT NULL,
  PHONE varchar(255) NOT NULL,
  STATUS varchar(255) NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  TRAINING_CENTER_COUNTRY_ID_FK bigint NOT NULL,
  PRIMARY KEY (CENTER_ID)
);



--
-- Structure de la table app_training_center_activity
--

CREATE TABLE  app_training_center_activity (
  TRAINING_CENTER_ACTIVITY_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  ACTIVITY_NAME varchar(255) NOT NULL,
  MIN_NUMBER bigint NOT NULL,
  MAX_NUMBER bigint NOT NULL,
  URL_VIDEO varchar(255) NOT NULL,
  MIN_AGE bigint NOT NULL,
  MAX_AGE bigint NOT NULL,
  DURATION_ACTIVITY bigint NOT NULL,
  EXERCICE_ACTIVITY_ID_FK bigint NOT NULL,
  DOCUMENT_ID_FK bigint NOT NULL,
  USER_ACTIVITY_ID_FK bigint NOT NULL,
  TRAINING_CENTER_ACTIVITY_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (TRAINING_CENTER_ACTIVITY_ID)
) ;

-- --------------------------------------------------------

--
-- Structure de la table app_training_center_agenda
--

CREATE TABLE  app_training_center_agenda (
  TRAINING_CENTER_AGENDA_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  EVENT_DATE timestamp NOT NULL,
  START_HOUR timestamp NOT NULL,
  END_HOUR timestamp NOT NULL,
  PLANNED_Number bigint NOT NULL,
  MIN_AGE bigint NOT NULL,
  MAX_AGE bigint NOT NULL,
  STATUS_AGENDA varchar(255) NOT NULL,
  USER_AGENDA_ID_FK bigint NOT NULL,
  TEACHER_AGENDA_ID_FK bigint NOT NULL,
  DOCUMENT_AGENDA_ID_FK bigint NOT NULL,
  ACTIVITY_ID_FK bigint NOT NULL,
  CLASS_ID_FK bigint NOT NULL,
  EXERCICE_AGENDA_ID_FK bigint NOT NULL,
  FILE_AGENDA_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (TRAINING_CENTER_AGENDA_ID)
) ;

-- --------------------------------------------------------

--
-- Structure de la table app_training_center_class
--

CREATE TABLE  app_training_center_class (
  TRAINING_CENTER_CLASS_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  CLASS_NAME varchar(255) NOT NULL,
  TEACHER_USER_ID_FK bigint NULL,
  TRAINING_CENTER_ID_FK bigint NOT NULL,
  PROGRAM_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (TRAINING_CENTER_CLASS_ID)
);


--
-- Structure de la table app_training_center_member
--

CREATE TABLE  app_training_center_member (
  TRAINING_CENTER_MEMBER_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Status varchar(255) NOT NULL,
  ROLE varchar(255) NOT NULL,
  START_DATE timestamp NOT NULL ,
  RELEASE_DATE timestamp NULL,
  MEMBER_USER_ID_FK bigint NOT NULL,
  TRAINING_CENTER_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (TRAINING_CENTER_MEMBER_ID)
) ;



--
-- Structure de la table app_training_center_program
--

CREATE TABLE  app_training_center_program (
  TRAINING_CENTER_PROGRAM_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  PROGRAM_DURATION bigint NOT NULL,
  PROGRAM_NAME varchar(255) NOT NULL,
  TRAINING_CENTER_PROGRAM_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (TRAINING_CENTER_PROGRAM_ID)
) ;

-- --------------------------------------------------------

--
-- Structure de la table app_training_center_program_activity
--

CREATE TABLE  app_training_center_program_activity (
  TRAINING_CENTER_PROGRAM_ACTIVITY_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  PROGRAM_ORDRE bigint NOT NULL,
  PROGRAM_ID_FK bigint NOT NULL,
  ACTIVITY_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (TRAINING_CENTER_PROGRAM_ACTIVITY_ID)
) ;

-- --------------------------------------------------------
-- --------------------------------------------------------

--
-- Structure de la table app_template_mail
--


CREATE TABLE  app_template_mail (
  ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  OBJECT varchar(100) NOT NULL,
  BODY varchar(10000) NOT NULL,
  EMAIL_KEY varchar(200) NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (ID)
) ;

--
-- Structure de la table app_training_center_student
--

CREATE TABLE  app_training_center_student (
  tcStudentId bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  STUDENT_USER_ID_FK bigint NOT NULL,
  TRAINING_CENTER_CLASS_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (tcStudentId)
);



--
-- Structure de la table app_training_center_theme
--

CREATE TABLE  app_training_center_theme (
  TRAINING_CENTER_THEME_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  THEME_NAME varchar(255) NOT NULL,
  THEME_DESCRIPTION varchar(255) NOT NULL,
  THEME_ORDRE bigint NOT NULL,
  PROGRAM_THEME_ID_FK bigint NOT NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  PRIMARY KEY (TRAINING_CENTER_THEME_ID)
);

-- --------------------------------------------------------

--
-- Structure de la table app_user
--

CREATE TABLE  app_user (
  USER_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  USER_EMAIL varchar(255) NULL,
  USER_PASSWORD varchar(255) NULL,
  CREATION_DATE timestamp NOT NULL ,
  UPDATING_DATE timestamp NOT NULL ,
  DELETING_DATE timestamp NULL,
  USER_NAME varchar(255) NOT NULL,
  FIRST_NAME varchar(255) NOT NULL,
  LAST_NAME varchar(255) NOT NULL,
  ADRESS varchar(255) NOT NULL,
  COUNTRY_ID_FK bigint NOT NULL,
  PHONE varchar(255) NOT NULL,
  STATUS varchar(255) NOT NULL,
  facebook_id varchar(255) NULL,
  google_id varchar(255) NULL,
  BIRTHDAY date NOT NULL,
  PICTURE_ID_FK bigint NULL,
  PRIMARY KEY (USER_ID)
);



--
-- Contraintes pour la table app_category
--
ALTER TABLE app_category
  ADD CONSTRAINT CATEGORY_PARENT_ID_FK FOREIGN KEY (CATEGORY_PARENT_ID_FK) REFERENCES app_category (CATEGORY_ID);
  ALTER TABLE app_category ADD CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID_FK) REFERENCES app_user (USER_ID);

--
-- Contraintes pour la table app_exercice
--
ALTER TABLE app_exercice
  ADD CONSTRAINT CATEGORY_ID_FK FOREIGN KEY (CATEGORY_ID_FK) REFERENCES app_category (CATEGORY_ID);
 ALTER TABLE app_exercice ADD CONSTRAINT EXERCICE_FILE_ID_FK FOREIGN KEY (EXERCICE_FILE_ID_FK) REFERENCES app_file (FILE_ID);
  ALTER TABLE app_exercice ADD CONSTRAINT PICTURE_ID_FK FOREIGN KEY (PICTURE_ID_FK) REFERENCES app_file (FILE_ID);
  ALTER TABLE app_exercice ADD CONSTRAINT USER_EXECICE_ID_FK FOREIGN KEY (USER_EXECICE_ID_FK) REFERENCES app_exercice (EXERCICE_ID);

--
-- Contraintes pour la table app_family
--

ALTER TABLE app_family
  ADD CONSTRAINT COUNTRY_FAMILY_ID_FK FOREIGN KEY (COUNTRY_ID_FK) REFERENCES app_country (ID);
ALTER TABLE app_family ADD CONSTRAINT LOGO_FILE_ID_FK FOREIGN KEY (LOGO_FILE_ID_FK) REFERENCES app_file (FILE_ID);
ALTER TABLE app_family  ADD CONSTRAINT MANAGER_USER_ID_FK FOREIGN KEY (MANAGER_USER_ID_FK) REFERENCES app_user (USER_ID);
--
-- Contraintes pour la table app_family_member
--
ALTER TABLE app_family_member
  ADD CONSTRAINT FAMILY_ID_FK FOREIGN KEY (FAMILY_ID_FK) REFERENCES app_family (FAMILY_ID);
 ALTER TABLE app_family_member ADD CONSTRAINT USER_FAMILY_MEMBER_ID_FK FOREIGN KEY (USER_ID_FK) REFERENCES app_user (USER_ID);

--
-- Contraintes pour la table app_file
--
ALTER TABLE app_file
  ADD CONSTRAINT USER_FILE_ID_FK FOREIGN KEY (USER_FILE_ID_FK) REFERENCES app_user (USER_ID);

--
-- Contraintes pour la table app_history
--
ALTER TABLE app_history
  ADD CONSTRAINT EXERCICE_ID_FK FOREIGN KEY (EXERCICE_ID_FK) REFERENCES app_exercice (EXERCICE_ID);
 ALTER TABLE app_history ADD CONSTRAINT USER_HISTORY_ID_FK FOREIGN KEY (USER_ID_FK) REFERENCES app_user (USER_ID);

--
-- Contraintes pour la table app_reviews
--
ALTER TABLE app_reviews
  ADD CONSTRAINT EXERCICE_REVIEWS_ID_FK	 FOREIGN KEY (EXERCICE_ID_FK) REFERENCES app_exercice (EXERCICE_ID);
ALTER TABLE app_reviews  ADD CONSTRAINT USER_REVIEWS_ID_FK FOREIGN KEY (USER_ID_FK) REFERENCES app_user (USER_ID);

--
-- Contraintes pour la table app_role
--
ALTER TABLE app_role
  ADD CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES app_user (USER_ID);

--
-- Contraintes pour la table app_training_center
--
ALTER TABLE app_training_center
  ADD CONSTRAINT TRAINING_CENTER_LOGO_FILE_ID_FK FOREIGN KEY (LOGO_FILE_ID_FK) REFERENCES app_file (FILE_ID);
 ALTER TABLE app_training_center ADD CONSTRAINT TRAINING_CENTER_MANAGER_USER_ID_FK FOREIGN KEY (MANAGER_USER_ID_FK) REFERENCES app_user (USER_ID);

--
-- Contraintes pour la table app_training_center_activity
--
ALTER TABLE app_training_center_activity
  ADD CONSTRAINT TRAINING_CENTER_ACTIVITY_ID_FK FOREIGN KEY (TRAINING_CENTER_ACTIVITY_ID_FK) REFERENCES app_training_center_activity (TRAINING_CENTER_ACTIVITY_ID);
 ALTER TABLE app_training_center_activity ADD CONSTRAINT DOCUMENT_ID_FK FOREIGN KEY (DOCUMENT_ID_FK) REFERENCES app_file (FILE_ID);
 ALTER TABLE app_training_center_activity ADD CONSTRAINT EXERCICE_ACTIVITY_ID_FK FOREIGN KEY (EXERCICE_ACTIVITY_ID_FK) REFERENCES app_exercice (EXERCICE_ID);
 ALTER TABLE app_training_center_activity ADD CONSTRAINT USER_ACTIVITY_ID_FK FOREIGN KEY (USER_ACTIVITY_ID_FK) REFERENCES app_user (USER_ID);

--
-- Contraintes pour la table app_training_center_agenda
--
ALTER TABLE app_training_center_agenda
  ADD CONSTRAINT TEACHER_AGENDA_ID_FK FOREIGN KEY (TEACHER_AGENDA_ID_FK) REFERENCES app_training_center_member (TRAINING_CENTER_MEMBER_ID);
ALTER TABLE app_training_center_agenda  ADD CONSTRAINT ACTIVITY_AGENDA_ID_FK FOREIGN KEY (ACTIVITY_ID_FK) REFERENCES app_training_center_activity (TRAINING_CENTER_ACTIVITY_ID);
ALTER TABLE app_training_center_agenda  ADD CONSTRAINT CLASS_AGENDA_ID_FK FOREIGN KEY (CLASS_ID_FK) REFERENCES app_training_center_class (TRAINING_CENTER_CLASS_ID);
ALTER TABLE app_training_center_agenda  ADD CONSTRAINT DOCUMENT_AGENDA_ID_FK FOREIGN KEY (DOCUMENT_AGENDA_ID_FK) REFERENCES app_file (FILE_ID);
ALTER TABLE app_training_center_agenda  ADD CONSTRAINT EXERCICE_AGENDA_ID_FK FOREIGN KEY (EXERCICE_AGENDA_ID_FK) REFERENCES app_exercice (EXERCICE_ID);
ALTER TABLE app_training_center_agenda  ADD CONSTRAINT FILE_AGENDA_ID_FK FOREIGN KEY (FILE_AGENDA_ID_FK) REFERENCES app_file (FILE_ID);
 ALTER TABLE app_training_center_agenda ADD CONSTRAINT USER_AGENDA_ID_FK FOREIGN KEY (USER_AGENDA_ID_FK) REFERENCES app_user (USER_ID);

--
-- Contraintes pour la table app_training_center_class
--
ALTER TABLE app_training_center_class
  ADD CONSTRAINT TRAINING_CENTER_ID_FK_2 FOREIGN KEY (TRAINING_CENTER_ID_FK) REFERENCES app_training_center (CENTER_ID);
ALTER TABLE app_training_center_class  ADD CONSTRAINT TEACHER_USER_ID_FK FOREIGN KEY (TEACHER_USER_ID_FK) REFERENCES app_user (USER_ID);

--
-- Contraintes pour la table app_training_center_member
--
ALTER TABLE app_training_center_member
  ADD CONSTRAINT CENTER_MEMBER_ID_FK FOREIGN KEY (TRAINING_CENTER_ID_FK) REFERENCES app_training_center (CENTER_ID);
 ALTER TABLE app_training_center_member ADD CONSTRAINT MEMBER_USER_ID_FK FOREIGN KEY (MEMBER_USER_ID_FK) REFERENCES app_user (USER_ID);

--
-- Contraintes pour la table app_training_center_program
--
ALTER TABLE app_training_center_program
  ADD CONSTRAINT TRAINING_CENTER_PROGRAM_ID_FK FOREIGN KEY (TRAINING_CENTER_PROGRAM_ID_FK) REFERENCES app_training_center (CENTER_ID);

--
-- Contraintes pour la table app_training_center_program_activity
--
ALTER TABLE app_training_center_program_activity
  ADD CONSTRAINT PROGRAM_ID_FK FOREIGN KEY (PROGRAM_ID_FK) REFERENCES app_training_center_program_activity (TRAINING_CENTER_PROGRAM_ACTIVITY_ID);
ALTER TABLE app_training_center_program_activity  ADD CONSTRAINT ACTIVITY_ID_FK FOREIGN KEY (ACTIVITY_ID_FK) REFERENCES app_training_center_activity (TRAINING_CENTER_ACTIVITY_ID);

--
-- Contraintes pour la table app_training_center_student
--
ALTER TABLE app_training_center_student
  ADD CONSTRAINT STUDENT_USER_ID_FK FOREIGN KEY (STUDENT_USER_ID_FK) REFERENCES app_user (USER_ID);
 ALTER TABLE app_training_center_student ADD CONSTRAINT TRAINING_CENTER_CLASS_ID_FK FOREIGN KEY (TRAINING_CENTER_CLASS_ID_FK) REFERENCES app_training_center_class (TRAINING_CENTER_CLASS_ID);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
